INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Nansensgade 18','Lorem ipsum dolor',1);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Blaagardsplads 17','Lorem ipsum dolor',1);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Frederiksberg Allé 14','Lorem ipsum dolor',1);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Rådhuspladsen 16','Lorem ipsum dolor',2);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Violvej 15','Lorem ipsum dolor',2);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Nansensgade 18','Lorem ipsum dolor',3);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Blaagardsplads 17','Lorem ipsum dolor',4);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Frederiksberg Allé 14','Lorem ipsum dolor',4);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Rådhuspladsen 16','Lorem ipsum dolor',4);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Violvej 15','Lorem ipsum dolor',15);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Nansensgade 18','Lorem ipsum dolor',15);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Blaagardsplads 17','Lorem ipsum dolor',16);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Frederiksberg Allé 14','Lorem ipsum dolor',16);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Rådhuspladsen 16','Lorem ipsum dolor',300);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Violvej 15','Lorem ipsum dolor',301);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Nansensgade 18','Lorem ipsum dolor',302);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Blaagardsplads 17','Lorem ipsum dolor',303);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Frederiksberg Allé 14','Lorem ipsum dolor',450);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Rådhuspladsen 16','Lorem ipsum dolor',451);
INSERT INTO address (address_street, address_info, fk_cityinfo_id) VALUES ('Violvej 15','Lorem ipsum dolor',452);

INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('jesper@andersen.dk',1);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('anders@softsolo.dk',2);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('thomas@softsolo.dk',2);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('kasper@andersen.dk',3);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('kristoffer@andersen.dk',4);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('joakim@andersen.dk',5);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('karsten@jal.dk',6);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('ole@jal.dk',6);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('kurt@andersen.dk',7);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('steen@andersen.dk',8);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('viggo@cpsol.dk',9);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('viktor@cpsol.dk',9);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('nikolaj@andersen.dk',10);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('jens@andersen.dk',11);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('john@engholm.dk',12);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('leon@engholm.dk',12);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('elias@andersen.dk',13);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('kristian@andersen.dk',14);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('michael@andersen.dk',15);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('lukas@andersen.dk',16);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('hans@andersen.dk',17);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('klaus@unit.dk',18);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('frans@unit.dk',18);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('stig@andersen.dk',19);
INSERT INTO infoentity (infoentity_email, fk_address_id) VALUES ('bo@andersen.dk',20);

INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (88888888,'Privat',1);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (77777777,'Privat',2);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (66666666,'Privat',3);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (55555555,'Privat',4);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (44444444,'Privat',5);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (33333333,'Privat',6);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (22222222,'Privat',7);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (11111111,'Privat',7);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (12345678,'Privat',8);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (87654321,'Privat',9);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (56895655,'Privat',10);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (78945621,'Privat',11);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (43243253,'Privat',12);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (54531231,'Privat',13);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (53484943,'Privat',14);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (98989874,'Privat',14);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (90849393,'Privat',15);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (36782100,'Privat',16);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (36009877,'Privat',16);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (49339399,'Privat',17);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (34145243,'Privat',18);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (43243243,'Privat',19);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (12341123,'Privat',20);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (12344321,'Privat',21);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (23455432,'Privat',22);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (34566534,'Privat',23);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (45677654,'Privat',23);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (56788765,'Privat',24);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (39201293,'Privat',25);
INSERT INTO phone (phone_number, phone_desc, fk_infoentity_id) VALUES (10293848,'Privat',25);

INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Jens','Jensen',1);
INSERT INTO company (company_name, company_desc, company_cvr, company_numemployees, company_marketvalue, fk_infoentity_id) VALUES ('Empire','Lorem ipsum dolor','dsa5',27,100000,2);
INSERT INTO company (company_name, company_desc, company_cvr, company_numemployees, company_marketvalue, fk_infoentity_id) VALUES ('Twitter','Lorem ipsum dolor','wq5',27,100000,3);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Anders','Andersen',4);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Ib','Ibsen',5);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Hans','Hansen',6);
INSERT INTO company (company_name, company_desc, company_cvr, company_numemployees, company_marketvalue, fk_infoentity_id) VALUES ('Google','Lorem ipsum dolor','d21ds',27,100000,7);
INSERT INTO company (company_name, company_desc, company_cvr, company_numemployees, company_marketvalue, fk_infoentity_id) VALUES ('Disney','Lorem ipsum dolor','5t4fd',27,100000,8);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Klavs','',9);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Klavsen','',10);
INSERT INTO company (company_name, company_desc, company_cvr, company_numemployees, company_marketvalue, fk_infoentity_id) VALUES ('Amazon','Lorem ipsum dolor','d21dsa',27,100000,11);
INSERT INTO company (company_name, company_desc, company_cvr, company_numemployees, company_marketvalue, fk_infoentity_id) VALUES ('Nestle','Lorem ipsum dolor','432f',27,100000,12);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Kristoffer','Kristoffersen',13);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Christian','Christiansen',14);
INSERT INTO company (company_name, company_desc, company_cvr, company_numemployees, company_marketvalue, fk_infoentity_id) VALUES ('Nike','Lorem ipsum dolor','1dda',27,100000,15);
INSERT INTO company (company_name, company_desc, company_cvr, company_numemployees, company_marketvalue, fk_infoentity_id) VALUES ('Stadium','Lorem ipsum dolor','d21',27,100000,16);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Ludvig','Ludvigsen',17);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Tom','Tomsen',18);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Casper','Christensen',19);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Frank','Hvam',20);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Tobias','Dybvad',21);
INSERT INTO company (company_name, company_desc, company_cvr, company_numemployees, company_marketvalue, fk_infoentity_id) VALUES ('Adidas','Lorem ipsum dolor','ab12',27,100000,22);
INSERT INTO company (company_name, company_desc, company_cvr, company_numemployees, company_marketvalue, fk_infoentity_id) VALUES ('Arla','Lorem ipsum dolor','cb23',27,100000,23);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Christian','Fuhlendorf',24);
INSERT INTO person (person_firstname, person_lastname, fk_infoentity_id) VALUES ('Anders','And',25);

INSERT INTO hobby (hobby_name, hobby_desc) VALUES ('Skiskydning','Lorem ipsum dolor');
INSERT INTO hobby (hobby_name, hobby_desc) VALUES ('Dværgkastning','Lorem ipsum dolor');
INSERT INTO hobby (hobby_name, hobby_desc) VALUES ('At jodle','Lorem ipsum dolor');
INSERT INTO hobby (hobby_name, hobby_desc) VALUES ('UFO jagt','Lorem ipsum dolor');
INSERT INTO hobby (hobby_name, hobby_desc) VALUES ('Ølsmagning','Lorem ipsum dolor');

INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(1,1);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(2,2);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(1,3);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(3,3);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(4,4);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(3,5);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(4,5);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(5,5);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(1,6);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(2,7);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(3,7);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(4,7);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(3,8);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(4,9);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(5,10);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(1,11);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(2,12);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(3,13);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(4,14);
INSERT INTO hobbyperson(fk_hobby_id, fk_person_id) VALUES(5,15);